// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqiwaltxobauzktzwucm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaXdhbHR4b2JhdXprdHp3dWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDI2MjgsImV4cCI6MjA3NDI3ODYyOH0.2CbrC9v7iWqP-PJhP6kiG6SG8rGLNGwxPhbd8EBGDrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});